### PR TITLE
install script with bacalhau install and w3s token prompt

### PR DESCRIPTION
**Pull request by acashmoney**
Tested on fresh p3 instance.

w3s token prompt was incorporated because I could not find a reliable way to share this secret and keep it hidden from the end user. This may need to be a future ticket.

For the WEB3STORAGE_TOKEN value to apply via the the install script, the following command needs to be run in the `plex` working directory. This is necessary for the env variable to be assigned to the correct hierarchical shell.

```
source install.sh
```
instead of
```
./install.sh
```

### CODE REVIEW

**Review by NiklasTR — CHANGES_REQUESTED** [review]
This is good!

- [ ]  I think the experience we want, however, is identical to the UX of installing plex / can you also update the README and change the script so that is can be a one-liner? 
- [ ] Also, I think we should integrate the installation of the go package in this installer - I am not seeing this here. Where should that be added?

**Comment by NiklasTR** [comment]
As I can see it right now, we want these three steps - all in one command:
image

The final command should look something like this
```
curl -sL https://raw.githubusercontent.com/labdao/ganglia/main/install.sh | bash
```

**Review by thetechnocrat-dev — APPROVED** [review]
:shipit:

**Comment by acashmoney** [comment]
> * [ ]   I think the experience we want, however, is identical to the UX of installing plex / can you also update the README and change the script so that is can be a one-liner?

New install script is a one-liner. See README.md in `plex` for reference

> * [ ]  Also, I think we should integrate the installation of the go package in this installer - I am not seeing this here. Where should that be added?

No longer needed to install Go. Pre-built binaries are included now for 4 OS/architecture combinations. See `plex/releases`

**Pull request merged**
